%{
#include "hpp.hpp"
%}
%defines %union { Sym*o; }
%token <o> SYM STR NUM
%token <o> LQ RQ
%token <o> EQ AT
%type <o> ex scalar list
%%
REPL: | REPL ex 	{ cout << $2->eval(glob)->dump() <<"\n"; } ;
ex	: scalar
	| LQ list RQ	{ $$=$2; }
	| ex EQ ex		{ $$=$2; $$->push($1); $$->push($3); }	
	| ex AT ex		{ $$=$2; $$->push($1); $$->push($3); }	
;
scalar : SYM | STR | NUM ;
list :				{ $$=new List(); }
	 | list ex		{ $$=$1; $$->push($2); } ;
%%
